// Generated by csql2go - do not edit

package mydb

/*
#cgo LDFLAGS: -lsqlite3
#include <stdlib.h>
#include "queries.h"
extern void mydb_Boat_cb(Boat *row, void *ctx);
extern void mydb_Competitor_cb(Competitor *row, void *ctx);
extern void mydb_Catch_cb(Catch *row, void *ctx);
*/
import "C"

import (
	"errors"
	"fmt"
	"runtime/cgo"
	"unsafe"
)

var ErrClosed = errors.New("mydb: use of closed database connection")

type Boat struct {
	ID int64
	Name string
	Registration string
}

type Competitor struct {
	ID int64
	FirstName string
	LastName string
	Email *string
	BoatID *int64
}

type Catch struct {
	ID int64
	CompetitorID int64
	Species string
	WeightGrams int64
	CaughtAt string
}

type CreateBoatParams struct {
	Name string
	Registration string
}

type CreateCompetitorParams struct {
	FirstName string
	LastName string
	Email string
	BoatID int64
}

type CreateCompetitorNoContactParams struct {
	FirstName string
	LastName string
}

type UpdateCompetitorEmailParams struct {
	Email string
	ID int64
}

type CreateCatchParams struct {
	CompetitorID int64
	Species string
	WeightGrams int64
	CaughtAt string
}

type DB struct {
	db     *C.sqlite3
	closed bool
}

func Open(path string) (*DB, error) {
	cpath := C.CString(path)
	defer C.free(unsafe.Pointer(cpath))
	var db *C.sqlite3
	rc := C.sqlite3_open(cpath, &db)
	if rc != C.SQLITE_OK {
		msg := "cannot open database"
		if db != nil {
			msg = C.GoString(C.sqlite3_errmsg(db))
			C.sqlite3_close(db)
		}
		return nil, fmt.Errorf("mydb: open: %s", msg)
	}
	return &DB{db: db}, nil
}

func (d *DB) Close() error {
	if d.closed {
		return nil
	}
	rc := C.sqlite3_close(d.db)
	d.closed = true
	if rc != C.SQLITE_OK {
		return fmt.Errorf("mydb: close: %s", C.GoString(C.sqlite3_errmsg(d.db)))
	}
	return nil
}

func (d *DB) err() error {
	return fmt.Errorf("mydb: %s", C.GoString(C.sqlite3_errmsg(d.db)))
}

//export mydb_Boat_cb
func mydb_Boat_cb(row *C.Boat, ctx unsafe.Pointer) {
	h := cgo.Handle(*(*C.uintptr_t)(ctx))
	acc := h.Value().(*[]Boat)
	var out Boat
	out.ID = int64(row.id)
	out.Name = C.GoStringN((*C.char)(unsafe.Pointer(row.name.data)), C.int(row.name.len))
	out.Registration = C.GoStringN((*C.char)(unsafe.Pointer(row.registration.data)), C.int(row.registration.len))
	*acc = append(*acc, out)
}

//export mydb_Competitor_cb
func mydb_Competitor_cb(row *C.Competitor, ctx unsafe.Pointer) {
	h := cgo.Handle(*(*C.uintptr_t)(ctx))
	acc := h.Value().(*[]Competitor)
	var out Competitor
	out.ID = int64(row.id)
	out.FirstName = C.GoStringN((*C.char)(unsafe.Pointer(row.first_name.data)), C.int(row.first_name.len))
	out.LastName = C.GoStringN((*C.char)(unsafe.Pointer(row.last_name.data)), C.int(row.last_name.len))
	if !row.email.null {
		v := C.GoStringN(row.email.data, C.int(row.email.len))
		out.Email = &v
	}
	if !row.boat_id.null {
		v := int64(row.boat_id.value)
		out.BoatID = &v
	}
	*acc = append(*acc, out)
}

//export mydb_Catch_cb
func mydb_Catch_cb(row *C.Catch, ctx unsafe.Pointer) {
	h := cgo.Handle(*(*C.uintptr_t)(ctx))
	acc := h.Value().(*[]Catch)
	var out Catch
	out.ID = int64(row.id)
	out.CompetitorID = int64(row.competitor_id)
	out.Species = C.GoStringN((*C.char)(unsafe.Pointer(row.species.data)), C.int(row.species.len))
	out.WeightGrams = int64(row.weight_grams)
	out.CaughtAt = C.GoStringN((*C.char)(unsafe.Pointer(row.caught_at.data)), C.int(row.caught_at.len))
	*acc = append(*acc, out)
}

// insert into boat (name, registration)
// values (:name, :registration)
// returning *;
func (d *DB) CreateBoat(params CreateBoatParams) (*Boat, error) {
	if d.closed {
		return nil, ErrClosed
	}
	var cparams C.CreateBoatParams
	p0Cstr := C.CString(params.Name)
	defer C.free(unsafe.Pointer(p0Cstr))
	f0 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p0Cstr)), len: C.size_t(len(params.Name))}
	cparams.name = f0
	p1Cstr := C.CString(params.Registration)
	defer C.free(unsafe.Pointer(p1Cstr))
	f1 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p1Cstr)), len: C.size_t(len(params.Registration))}
	cparams.registration = f1
	var acc []Boat
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.create_boat_cb(d.db, &cparams, (*[0]byte)(C.mydb_Boat_cb), unsafe.Pointer(&hctx))
	if rc == C.SQLITE_NOTFOUND {
		return nil, nil
	}
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return &acc[0], nil
}

// select * from boat where id = :id;
func (d *DB) GetBoat(id int64) (*Boat, error) {
	if d.closed {
		return nil, ErrClosed
	}
	cID := C.sql_int64(id)
	var acc []Boat
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.get_boat_cb(d.db, cID, (*[0]byte)(C.mydb_Boat_cb), unsafe.Pointer(&hctx))
	if rc == C.SQLITE_NOTFOUND {
		return nil, nil
	}
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return &acc[0], nil
}

// select * from boat order by name;
func (d *DB) ListBoats() ([]Boat, error) {
	if d.closed {
		return nil, ErrClosed
	}
	var acc []Boat
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.list_boats_cb(d.db, (*[0]byte)(C.mydb_Boat_cb), unsafe.Pointer(&hctx))
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return acc, nil
}

// insert into competitor (first_name, last_name, email, boat_id)
// values (:first_name, :last_name, :email, :boat_id)
// returning *;
func (d *DB) CreateCompetitor(params CreateCompetitorParams) (*Competitor, error) {
	if d.closed {
		return nil, ErrClosed
	}
	var cparams C.CreateCompetitorParams
	p0Cstr := C.CString(params.FirstName)
	defer C.free(unsafe.Pointer(p0Cstr))
	f0 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p0Cstr)), len: C.size_t(len(params.FirstName))}
	cparams.first_name = f0
	p1Cstr := C.CString(params.LastName)
	defer C.free(unsafe.Pointer(p1Cstr))
	f1 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p1Cstr)), len: C.size_t(len(params.LastName))}
	cparams.last_name = f1
	p2Cstr := C.CString(params.Email)
	defer C.free(unsafe.Pointer(p2Cstr))
	f2 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p2Cstr)), len: C.size_t(len(params.Email))}
	cparams.email = f2
	f3 := C.sql_int64(params.BoatID)
	cparams.boat_id = f3
	var acc []Competitor
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.create_competitor_cb(d.db, &cparams, (*[0]byte)(C.mydb_Competitor_cb), unsafe.Pointer(&hctx))
	if rc == C.SQLITE_NOTFOUND {
		return nil, nil
	}
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return &acc[0], nil
}

// insert into competitor (first_name, last_name)
// values (:first_name, :last_name)
// returning *;
func (d *DB) CreateCompetitorNoContact(params CreateCompetitorNoContactParams) (*Competitor, error) {
	if d.closed {
		return nil, ErrClosed
	}
	var cparams C.CreateCompetitorNoContactParams
	p0Cstr := C.CString(params.FirstName)
	defer C.free(unsafe.Pointer(p0Cstr))
	f0 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p0Cstr)), len: C.size_t(len(params.FirstName))}
	cparams.first_name = f0
	p1Cstr := C.CString(params.LastName)
	defer C.free(unsafe.Pointer(p1Cstr))
	f1 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p1Cstr)), len: C.size_t(len(params.LastName))}
	cparams.last_name = f1
	var acc []Competitor
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.create_competitor_no_contact_cb(d.db, &cparams, (*[0]byte)(C.mydb_Competitor_cb), unsafe.Pointer(&hctx))
	if rc == C.SQLITE_NOTFOUND {
		return nil, nil
	}
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return &acc[0], nil
}

// select * from competitor where id = :id;
func (d *DB) GetCompetitor(id int64) (*Competitor, error) {
	if d.closed {
		return nil, ErrClosed
	}
	cID := C.sql_int64(id)
	var acc []Competitor
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.get_competitor_cb(d.db, cID, (*[0]byte)(C.mydb_Competitor_cb), unsafe.Pointer(&hctx))
	if rc == C.SQLITE_NOTFOUND {
		return nil, nil
	}
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return &acc[0], nil
}

// select * from competitor order by last_name, first_name;
func (d *DB) ListCompetitors() ([]Competitor, error) {
	if d.closed {
		return nil, ErrClosed
	}
	var acc []Competitor
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.list_competitors_cb(d.db, (*[0]byte)(C.mydb_Competitor_cb), unsafe.Pointer(&hctx))
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return acc, nil
}

// update competitor set email = :email where id = :id;
func (d *DB) UpdateCompetitorEmail(params UpdateCompetitorEmailParams) error {
	if d.closed {
		return ErrClosed
	}
	var cparams C.UpdateCompetitorEmailParams
	p0Cstr := C.CString(params.Email)
	defer C.free(unsafe.Pointer(p0Cstr))
	f0 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p0Cstr)), len: C.size_t(len(params.Email))}
	cparams.email = f0
	f1 := C.sql_int64(params.ID)
	cparams.id = f1
	rc := C.update_competitor_email(d.db, &cparams)
	if rc != C.SQLITE_OK {
		return d.err()
	}
	return nil
}

// delete from competitor where id = :id;
func (d *DB) DeleteCompetitor(id int64) error {
	if d.closed {
		return ErrClosed
	}
	cID := C.sql_int64(id)
	rc := C.delete_competitor(d.db, cID)
	if rc != C.SQLITE_OK {
		return d.err()
	}
	return nil
}

// insert into catch (competitor_id, species, weight_grams, caught_at)
// values (:competitor_id, :species, :weight_grams, :caught_at)
// returning *;
func (d *DB) CreateCatch(params CreateCatchParams) (*Catch, error) {
	if d.closed {
		return nil, ErrClosed
	}
	var cparams C.CreateCatchParams
	f0 := C.sql_int64(params.CompetitorID)
	cparams.competitor_id = f0
	p1Cstr := C.CString(params.Species)
	defer C.free(unsafe.Pointer(p1Cstr))
	f1 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p1Cstr)), len: C.size_t(len(params.Species))}
	cparams.species = f1
	f2 := C.sql_int64(params.WeightGrams)
	cparams.weight_grams = f2
	p3Cstr := C.CString(params.CaughtAt)
	defer C.free(unsafe.Pointer(p3Cstr))
	f3 := C.sql_text{data: (*C.sql_byte)(unsafe.Pointer(p3Cstr)), len: C.size_t(len(params.CaughtAt))}
	cparams.caught_at = f3
	var acc []Catch
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.create_catch_cb(d.db, &cparams, (*[0]byte)(C.mydb_Catch_cb), unsafe.Pointer(&hctx))
	if rc == C.SQLITE_NOTFOUND {
		return nil, nil
	}
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return &acc[0], nil
}

// select * from catch where competitor_id = :competitor_id order by caught_at;
func (d *DB) ListCatchesByCompetitor(competitorID int64) ([]Catch, error) {
	if d.closed {
		return nil, ErrClosed
	}
	cCompetitorID := C.sql_int64(competitorID)
	var acc []Catch
	h := cgo.NewHandle(&acc)
	defer h.Delete()
	hctx := C.uintptr_t(h)
	rc := C.list_catches_by_competitor_cb(d.db, cCompetitorID, (*[0]byte)(C.mydb_Catch_cb), unsafe.Pointer(&hctx))
	if rc != C.SQLITE_OK {
		return nil, d.err()
	}
	return acc, nil
}

