// Generated by csql2lua - do not edit

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include "sqlite3.h"
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "../src/queries.h"

#define MOD_MT "basicdb.Connection"

typedef struct { sqlite3 *db; } basicdb_Handle;

static basicdb_Handle *basicdb_checkhandle(lua_State *L, int idx) {
    basicdb_Handle *h = (basicdb_Handle *)luaL_checkudata(L, idx, MOD_MT);
    if (!h->db) luaL_error(L, "attempt to use a closed 'basicdb' database connection");
    return h;
}

static int basicdb_open(lua_State *L) {
    const char *path = luaL_checkstring(L, 1);
    sqlite3 *db = NULL;
    int rc = sqlite3_open(path, &db);
    if (rc != SQLITE_OK) {
        char msg[256];
        snprintf(msg, sizeof(msg), "%s", db ? sqlite3_errmsg(db) : "cannot open database");
        if (db) sqlite3_close(db);
        return luaL_error(L, "%s", msg);
    }
    basicdb_Handle *h = (basicdb_Handle *)lua_newuserdata(L, sizeof(basicdb_Handle));
    h->db = db;
    luaL_getmetatable(L, MOD_MT);
    lua_setmetatable(L, -2);
    return 1;
}

static int basicdb_close(lua_State *L) {
    basicdb_Handle *h = (basicdb_Handle *)luaL_checkudata(L, 1, MOD_MT);
    if (h->db) { sqlite3_close(h->db); h->db = NULL; }
    return 0;
}

static int basicdb_tostring(lua_State *L) {
    basicdb_Handle *h = (basicdb_Handle *)luaL_checkudata(L, 1, MOD_MT);
    lua_pushfstring(L, "basicdb.Connection: %p%s", (void*)h, h->db ? "" : " (closed)");
    return 1;
}

// CreateBoat :one
typedef struct { lua_State *L; int idx; } basicdb_l_create_boat_ctx;
static void basicdb_l_create_boat_collect(Boat *row, void *vctx) {
    basicdb_l_create_boat_ctx *c = (basicdb_l_create_boat_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->name.data, row->name.len);
    lua_setfield(L, -2, "name");
    lua_pushlstring(L, (const char*)row->registration.data, row->registration.len);
    lua_setfield(L, -2, "registration");
}

static int basicdb_l_create_boat(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    CreateBoatParams params;
    { size_t n; const char *s = luaL_checklstring(L, 2, &n); params.name.data = (sql_byte*)s; params.name.len = n; }
    { size_t n; const char *s = luaL_checklstring(L, 3, &n); params.registration.data = (sql_byte*)s; params.registration.len = n; }
    basicdb_l_create_boat_ctx c = { L, 0 };
    int rc = create_boat_cb(h->db, &params, basicdb_l_create_boat_collect, &c);
    if (rc == SQLITE_NOTFOUND) { lua_pushnil(L); return 1; }
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    return 1;
}

// GetBoat :one
typedef struct { lua_State *L; int idx; } basicdb_l_get_boat_ctx;
static void basicdb_l_get_boat_collect(Boat *row, void *vctx) {
    basicdb_l_get_boat_ctx *c = (basicdb_l_get_boat_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->name.data, row->name.len);
    lua_setfield(L, -2, "name");
    lua_pushlstring(L, (const char*)row->registration.data, row->registration.len);
    lua_setfield(L, -2, "registration");
}

static int basicdb_l_get_boat(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    sql_int64 id;
    id = (sql_int64)luaL_checkinteger(L, 2);
    basicdb_l_get_boat_ctx c = { L, 0 };
    int rc = get_boat_cb(h->db, id, basicdb_l_get_boat_collect, &c);
    if (rc == SQLITE_NOTFOUND) { lua_pushnil(L); return 1; }
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    return 1;
}

// ListBoats :many
typedef struct { lua_State *L; int idx; } basicdb_l_list_boats_ctx;
static void basicdb_l_list_boats_collect(Boat *row, void *vctx) {
    basicdb_l_list_boats_ctx *c = (basicdb_l_list_boats_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->name.data, row->name.len);
    lua_setfield(L, -2, "name");
    lua_pushlstring(L, (const char*)row->registration.data, row->registration.len);
    lua_setfield(L, -2, "registration");
    lua_rawseti(L, -2, ++c->idx);
}

static int basicdb_l_list_boats(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    lua_newtable(L);
    basicdb_l_list_boats_ctx c = { L, 0 };
    int rc = list_boats_cb(h->db, basicdb_l_list_boats_collect, &c);
    if (rc != SQLITE_OK) { lua_pop(L, 1); return luaL_error(L, "%s", sqlite3_errmsg(h->db)); }
    return 1;
}

// CreateCompetitor :one
typedef struct { lua_State *L; int idx; } basicdb_l_create_competitor_ctx;
static void basicdb_l_create_competitor_collect(Competitor *row, void *vctx) {
    basicdb_l_create_competitor_ctx *c = (basicdb_l_create_competitor_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->first_name.data, row->first_name.len);
    lua_setfield(L, -2, "first_name");
    lua_pushlstring(L, (const char*)row->last_name.data, row->last_name.len);
    lua_setfield(L, -2, "last_name");
    if (row->email.null) lua_pushnil(L); else lua_pushlstring(L, (const char*)row->email.data, row->email.len);
    lua_setfield(L, -2, "email");
    if (row->boat_id.null) lua_pushnil(L); else lua_pushinteger(L, (lua_Integer)row->boat_id.value);
    lua_setfield(L, -2, "boat_id");
}

static int basicdb_l_create_competitor(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    CreateCompetitorParams params;
    { size_t n; const char *s = luaL_checklstring(L, 2, &n); params.first_name.data = (sql_byte*)s; params.first_name.len = n; }
    { size_t n; const char *s = luaL_checklstring(L, 3, &n); params.last_name.data = (sql_byte*)s; params.last_name.len = n; }
    { size_t n; const char *s = luaL_checklstring(L, 4, &n); params.email.data = (sql_byte*)s; params.email.len = n; }
    params.boat_id = (sql_int64)luaL_checkinteger(L, 5);
    basicdb_l_create_competitor_ctx c = { L, 0 };
    int rc = create_competitor_cb(h->db, &params, basicdb_l_create_competitor_collect, &c);
    if (rc == SQLITE_NOTFOUND) { lua_pushnil(L); return 1; }
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    return 1;
}

// CreateCompetitorNoContact :one
typedef struct { lua_State *L; int idx; } basicdb_l_create_competitor_no_contact_ctx;
static void basicdb_l_create_competitor_no_contact_collect(Competitor *row, void *vctx) {
    basicdb_l_create_competitor_no_contact_ctx *c = (basicdb_l_create_competitor_no_contact_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->first_name.data, row->first_name.len);
    lua_setfield(L, -2, "first_name");
    lua_pushlstring(L, (const char*)row->last_name.data, row->last_name.len);
    lua_setfield(L, -2, "last_name");
    if (row->email.null) lua_pushnil(L); else lua_pushlstring(L, (const char*)row->email.data, row->email.len);
    lua_setfield(L, -2, "email");
    if (row->boat_id.null) lua_pushnil(L); else lua_pushinteger(L, (lua_Integer)row->boat_id.value);
    lua_setfield(L, -2, "boat_id");
}

static int basicdb_l_create_competitor_no_contact(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    CreateCompetitorNoContactParams params;
    { size_t n; const char *s = luaL_checklstring(L, 2, &n); params.first_name.data = (sql_byte*)s; params.first_name.len = n; }
    { size_t n; const char *s = luaL_checklstring(L, 3, &n); params.last_name.data = (sql_byte*)s; params.last_name.len = n; }
    basicdb_l_create_competitor_no_contact_ctx c = { L, 0 };
    int rc = create_competitor_no_contact_cb(h->db, &params, basicdb_l_create_competitor_no_contact_collect, &c);
    if (rc == SQLITE_NOTFOUND) { lua_pushnil(L); return 1; }
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    return 1;
}

// GetCompetitor :one
typedef struct { lua_State *L; int idx; } basicdb_l_get_competitor_ctx;
static void basicdb_l_get_competitor_collect(Competitor *row, void *vctx) {
    basicdb_l_get_competitor_ctx *c = (basicdb_l_get_competitor_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->first_name.data, row->first_name.len);
    lua_setfield(L, -2, "first_name");
    lua_pushlstring(L, (const char*)row->last_name.data, row->last_name.len);
    lua_setfield(L, -2, "last_name");
    if (row->email.null) lua_pushnil(L); else lua_pushlstring(L, (const char*)row->email.data, row->email.len);
    lua_setfield(L, -2, "email");
    if (row->boat_id.null) lua_pushnil(L); else lua_pushinteger(L, (lua_Integer)row->boat_id.value);
    lua_setfield(L, -2, "boat_id");
}

static int basicdb_l_get_competitor(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    sql_int64 id;
    id = (sql_int64)luaL_checkinteger(L, 2);
    basicdb_l_get_competitor_ctx c = { L, 0 };
    int rc = get_competitor_cb(h->db, id, basicdb_l_get_competitor_collect, &c);
    if (rc == SQLITE_NOTFOUND) { lua_pushnil(L); return 1; }
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    return 1;
}

// ListCompetitors :many
typedef struct { lua_State *L; int idx; } basicdb_l_list_competitors_ctx;
static void basicdb_l_list_competitors_collect(Competitor *row, void *vctx) {
    basicdb_l_list_competitors_ctx *c = (basicdb_l_list_competitors_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushlstring(L, (const char*)row->first_name.data, row->first_name.len);
    lua_setfield(L, -2, "first_name");
    lua_pushlstring(L, (const char*)row->last_name.data, row->last_name.len);
    lua_setfield(L, -2, "last_name");
    if (row->email.null) lua_pushnil(L); else lua_pushlstring(L, (const char*)row->email.data, row->email.len);
    lua_setfield(L, -2, "email");
    if (row->boat_id.null) lua_pushnil(L); else lua_pushinteger(L, (lua_Integer)row->boat_id.value);
    lua_setfield(L, -2, "boat_id");
    lua_rawseti(L, -2, ++c->idx);
}

static int basicdb_l_list_competitors(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    lua_newtable(L);
    basicdb_l_list_competitors_ctx c = { L, 0 };
    int rc = list_competitors_cb(h->db, basicdb_l_list_competitors_collect, &c);
    if (rc != SQLITE_OK) { lua_pop(L, 1); return luaL_error(L, "%s", sqlite3_errmsg(h->db)); }
    return 1;
}

// UpdateCompetitorEmail :exec
static int basicdb_l_update_competitor_email(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    UpdateCompetitorEmailParams params;
    { size_t n; const char *s = luaL_checklstring(L, 2, &n); params.email.data = (sql_byte*)s; params.email.len = n; }
    params.id = (sql_int64)luaL_checkinteger(L, 3);
    int rc = update_competitor_email(h->db, &params);
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    lua_pushboolean(L, 1);
    return 1;
}

// DeleteCompetitor :exec
static int basicdb_l_delete_competitor(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    sql_int64 id;
    id = (sql_int64)luaL_checkinteger(L, 2);
    int rc = delete_competitor(h->db, id);
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    lua_pushboolean(L, 1);
    return 1;
}

// CreateCatch :one
typedef struct { lua_State *L; int idx; } basicdb_l_create_catch_ctx;
static void basicdb_l_create_catch_collect(Catch *row, void *vctx) {
    basicdb_l_create_catch_ctx *c = (basicdb_l_create_catch_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushinteger(L, (lua_Integer)row->competitor_id);
    lua_setfield(L, -2, "competitor_id");
    lua_pushlstring(L, (const char*)row->species.data, row->species.len);
    lua_setfield(L, -2, "species");
    lua_pushinteger(L, (lua_Integer)row->weight_grams);
    lua_setfield(L, -2, "weight_grams");
    lua_pushlstring(L, (const char*)row->caught_at.data, row->caught_at.len);
    lua_setfield(L, -2, "caught_at");
}

static int basicdb_l_create_catch(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    CreateCatchParams params;
    params.competitor_id = (sql_int64)luaL_checkinteger(L, 2);
    { size_t n; const char *s = luaL_checklstring(L, 3, &n); params.species.data = (sql_byte*)s; params.species.len = n; }
    params.weight_grams = (sql_int64)luaL_checkinteger(L, 4);
    { size_t n; const char *s = luaL_checklstring(L, 5, &n); params.caught_at.data = (sql_byte*)s; params.caught_at.len = n; }
    basicdb_l_create_catch_ctx c = { L, 0 };
    int rc = create_catch_cb(h->db, &params, basicdb_l_create_catch_collect, &c);
    if (rc == SQLITE_NOTFOUND) { lua_pushnil(L); return 1; }
    if (rc != SQLITE_OK) return luaL_error(L, "%s", sqlite3_errmsg(h->db));
    return 1;
}

// ListCatchesByCompetitor :many
typedef struct { lua_State *L; int idx; } basicdb_l_list_catches_by_competitor_ctx;
static void basicdb_l_list_catches_by_competitor_collect(Catch *row, void *vctx) {
    basicdb_l_list_catches_by_competitor_ctx *c = (basicdb_l_list_catches_by_competitor_ctx *)vctx;
    lua_State *L = c->L;
    lua_newtable(L);
    lua_pushinteger(L, (lua_Integer)row->id);
    lua_setfield(L, -2, "id");
    lua_pushinteger(L, (lua_Integer)row->competitor_id);
    lua_setfield(L, -2, "competitor_id");
    lua_pushlstring(L, (const char*)row->species.data, row->species.len);
    lua_setfield(L, -2, "species");
    lua_pushinteger(L, (lua_Integer)row->weight_grams);
    lua_setfield(L, -2, "weight_grams");
    lua_pushlstring(L, (const char*)row->caught_at.data, row->caught_at.len);
    lua_setfield(L, -2, "caught_at");
    lua_rawseti(L, -2, ++c->idx);
}

static int basicdb_l_list_catches_by_competitor(lua_State *L) {
    basicdb_Handle *h = basicdb_checkhandle(L, 1);
    sql_int64 competitor_id;
    competitor_id = (sql_int64)luaL_checkinteger(L, 2);
    lua_newtable(L);
    basicdb_l_list_catches_by_competitor_ctx c = { L, 0 };
    int rc = list_catches_by_competitor_cb(h->db, competitor_id, basicdb_l_list_catches_by_competitor_collect, &c);
    if (rc != SQLITE_OK) { lua_pop(L, 1); return luaL_error(L, "%s", sqlite3_errmsg(h->db)); }
    return 1;
}

static const luaL_Reg basicdb_methods[] = {
    { "close", basicdb_close },
    { "create_boat", basicdb_l_create_boat },
    { "get_boat", basicdb_l_get_boat },
    { "list_boats", basicdb_l_list_boats },
    { "create_competitor", basicdb_l_create_competitor },
    { "create_competitor_no_contact", basicdb_l_create_competitor_no_contact },
    { "get_competitor", basicdb_l_get_competitor },
    { "list_competitors", basicdb_l_list_competitors },
    { "update_competitor_email", basicdb_l_update_competitor_email },
    { "delete_competitor", basicdb_l_delete_competitor },
    { "create_catch", basicdb_l_create_catch },
    { "list_catches_by_competitor", basicdb_l_list_catches_by_competitor },
    { NULL, NULL }
};

int luaopen_basicdb(lua_State *L) {
    luaL_newmetatable(L, MOD_MT);
    lua_pushcfunction(L, basicdb_close);
    lua_setfield(L, -2, "__gc");
    lua_pushcfunction(L, basicdb_tostring);
    lua_setfield(L, -2, "__tostring");
    lua_newtable(L);
    luaL_setfuncs(L, basicdb_methods, 0);
    lua_setfield(L, -2, "__index");
    lua_pop(L, 1);

    lua_newtable(L);
    lua_pushcfunction(L, basicdb_open);
    lua_setfield(L, -2, "open");
    return 1;
}
