-- Exercises the basicdb Lua module generated by csql2lua from this example's
-- manifest.json. Run from the example root after building:
--
--   cmake -B build -S . && cmake --build build
--   lua lua/test.lua
--
-- (Set CSQL2LUA_MODULE_DIR to point elsewhere if your build directory isn't
-- ./build.)

local moddir = os.getenv("CSQL2LUA_MODULE_DIR") or "build"
package.cpath = moddir .. "/?.so;" .. package.cpath

local basicdb = require("basicdb")

local dbpath = os.tmpname()
os.remove(dbpath)

-- basicdb doesn't expose raw DDL execution (it only binds the queries from
-- queries.sql), so load the schema with the sqlite3 CLI before opening it
-- through the generated module.
local schema_path = (arg[0]:match("(.*/)") or "./") .. "../sql/schema.sql"
assert(os.execute(string.format('sqlite3 "%s" < "%s"', dbpath, schema_path)))

local db = assert(basicdb.open(dbpath))
print("connection:", tostring(db))

local boat = db:create_boat("Dawn Treader", "REG-001")
assert(boat.id == 1 and boat.name == "Dawn Treader")
print("create_boat:", boat.id, boat.name, boat.registration)

db:create_boat("Reel Deal", "REG-002")
local boats = db:list_boats()
assert(#boats == 2)
print("list_boats: " .. #boats .. " boats")

assert(db:get_boat(999) == nil)
print("get_boat(missing) -> nil, as expected")

local alice = db:create_competitor("Alice", "Nguyen", "alice@example.com", boat.id)
assert(alice.email == "alice@example.com" and alice.boat_id == boat.id)
print("create_competitor:", alice.first_name, alice.last_name, alice.email)

-- No email/boat given -> nullable columns come back as absent keys (SQL NULL -> Lua nil).
local bob = db:create_competitor_no_contact("Bob", "Reyes")
assert(bob.email == nil and bob.boat_id == nil)
print("create_competitor_no_contact: nullable fields are nil, as expected")

assert(db:update_competitor_email("bob@example.com", bob.id) == true)
assert(db:get_competitor(bob.id).email == "bob@example.com")
print("update_competitor_email: ok")

db:delete_competitor(bob.id)
assert(db:get_competitor(bob.id) == nil)
print("delete_competitor: ok")

local ok, err = pcall(function() return db:get_boat(1) end)
db:close()
assert(ok, "query before close should have succeeded: " .. tostring(err))

local ok2, err2 = pcall(function() return db:get_boat(1) end)
assert(ok2 == false and err2:find("closed"))
print("use after close -> error, as expected")

os.remove(dbpath)
print("ALL OK")
