const char runtime_lua_data[] =
	"-- Job-system runtime: JSON handling, canonical encoding, and handler\n"
	"-- dispatch. Embedded into the binary (see CMakeLists.txt / runtime_lua.h)\n"
	"-- and executed in each worker's lua_State, after the `jobq` module is\n"
	"-- published and before the user's handlers script (-l PATH) loads, so that\n"
	"-- script can contain nothing but jobq.register(kind, fn) calls.\n"
	"\n"
	"local jobq = require(\"jobq\")\n"
	"local dkjson = require(\"dkjson\")\n"
	"local cjson = {\n"
	"  encode = dkjson.encode,\n"
	"  decode = function(str)\n"
	"    local obj, _, err = dkjson.decode(str)\n"
	"    if err then return nil, err end\n"
	"    return obj\n"
	"  end,\n"
	"}\n"
	"\n"
	"-- Canonical JSON: sorted keys, so equal args => equal bytes. Uniqueness is\n"
	"-- byte-comparison; cjson.encode does NOT sort keys. Use this when building\n"
	"-- unique_key values at the producer side too.\n"
	"local function canonical_json(v)\n"
	"  local t = type(v)\n"
	"  if t == \"table\" then\n"
	"    local n = #v\n"
	"    if n > 0 then\n"
	"      local parts = {}\n"
	"      for i = 1, n do parts[i] = canonical_json(v[i]) end\n"
	"      return \"[\" .. table.concat(parts, \",\") .. \"]\"\n"
	"    end\n"
	"    local keys = {}\n"
	"    for k in pairs(v) do keys[#keys + 1] = k end\n"
	"    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)\n"
	"    local parts = {}\n"
	"    for i, k in ipairs(keys) do\n"
	"      parts[i] = cjson.encode(tostring(k)) .. \":\" .. canonical_json(v[k])\n"
	"    end\n"
	"    return \"{\" .. table.concat(parts, \",\") .. \"}\"\n"
	"  end\n"
	"  return cjson.encode(v)\n"
	"end\n"
	"_G.canonical_json = canonical_json\n"
	"\n"
	"local handlers = {}\n"
	"jobq.register = function(kind, fn) handlers[kind] = fn end\n"
	"\n"
	"-- Entry point called from C for every claimed job.\n"
	"function dispatch(id, kind, args_json)\n"
	"  local h = handlers[kind]\n"
	"  if not h then\n"
	"    error((\"no handler for kind %q\"):format(kind))\n"
	"  end\n"
	"  local args, err = cjson.decode(args_json)\n"
	"  if args == nil then\n"
	"    error((\"bad args JSON for job %d: %s\"):format(id, tostring(err)))\n"
	"  end\n"
	"  return h(args, { id = id, kind = kind })\n"
	"end\n"
	"";
const unsigned int runtime_lua_len = 1901;
