// sql2c basic example — a fishing-tournament schema (boat / competitor /
// catch) exercising :one, :many, :exec, single- and multi-param queries,
// and nullable result columns.
//
// queries.h, queries.c and models.h are generated by sql2c from
// ../sql/schema.sql and ../sql/queries.sql (see ../CMakeLists.txt).

#include <stdio.h>
#include <stdlib.h>

#include "sqlite3.h"
#include "models.h"
#include "queries.h"

#ifndef SCHEMA_PATH
#define SCHEMA_PATH "sql/schema.sql"
#endif

// ============================================================================
// A minimal bump allocator satisfying sql_allocator, so query results can
// outlive the sqlite3_stmt they came from. Real programs would plug in
// whatever arena/pool they already have.
// ============================================================================

typedef struct {
   char *base;
   size_t len;
   size_t cap;
} Arena;

static void *arena_alloc(void *ctx, size_t n) {
   Arena *a = ctx;
   n = (n + 15) & ~(size_t)15;
   if (a->len + n > a->cap) {
      fprintf(stderr, "example: arena exhausted\n");
      exit(1);
   }
   void *p = a->base + a->len;
   a->len += n;
   return p;
}

static char *read_file(const char *path) {
   FILE *f = fopen(path, "rb");
   if (!f) {
      fprintf(stderr, "example: cannot open %s\n", path);
      exit(1);
   }
   fseek(f, 0, SEEK_END);
   long n = ftell(f);
   fseek(f, 0, SEEK_SET);
   char *buf = malloc((size_t)n + 1);
   if (fread(buf, 1, (size_t)n, f) != (size_t)n) {
      fprintf(stderr, "example: short read on %s\n", path);
      exit(1);
   }
   buf[n] = 0;
   fclose(f);
   return buf;
}

static void die(sqlite3 *db, const char *what) {
   fprintf(stderr, "example: %s: %s\n", what, sqlite3_errmsg(db));
   exit(1);
}

// ============================================================================
// Print helpers
// ============================================================================

static void print_boat(Boat *b, void *ctx) {
   (void)ctx;
   printf("  boat #%lld %.*s (%.*s)\n", (long long)b->id, (int)b->name.len,
          (char *)b->name.data, (int)b->registration.len, (char *)b->registration.data);
}

static void print_competitor(Competitor *c) {
   printf("  competitor #%lld %.*s %.*s email=", (long long)c->id, (int)c->first_name.len,
          (char *)c->first_name.data, (int)c->last_name.len, (char *)c->last_name.data);
   if (c->email.null) printf("NULL");
   else printf("%.*s", (int)c->email.len, c->email.data);
   printf(" boat_id=");
   if (c->boat_id.null) printf("NULL");
   else printf("%lld", (long long)c->boat_id.value);
   printf("\n");
}

static void print_catch(Catch *c) {
   printf("  catch #%lld competitor=%lld species=%.*s weight=%lldg caught_at=%.*s\n",
          (long long)c->id, (long long)c->competitor_id, (int)c->species.len,
          (char *)c->species.data, (long long)c->weight_grams, (int)c->caught_at.len,
          (char *)c->caught_at.data);
}

int main(void) {
   sqlite3 *db;
   if (sqlite3_open(":memory:", &db) != SQLITE_OK) die(db, "open");

   char *schema = read_file(SCHEMA_PATH);
   char *err = NULL;
   if (sqlite3_exec(db, schema, NULL, NULL, &err) != SQLITE_OK) {
      fprintf(stderr, "example: schema: %s\n", err);
      return 1;
   }
   free(schema);

   static char arena_mem[64 * 1024];
   Arena arena = {arena_mem, 0, sizeof(arena_mem)};
   sql_allocator a = {arena_alloc, &arena};
   int rc;

   printf("== creating boats ==\n");
   Boat *dawn = create_boat(a, db,
                             &(CreateBoatParams){
                                 .name = to_sql_text("Dawn Treader"),
                                 .registration = to_sql_text("REG-001"),
                             },
                             &rc);
   print_boat(dawn, NULL);

   Boat *reel = create_boat(a, db,
                             &(CreateBoatParams){
                                 .name = to_sql_text("Reel Deal"),
                                 .registration = to_sql_text("REG-002"),
                             },
                             &rc);
   print_boat(reel, NULL);

   printf("\n== fetching a boat by id ==\n");
   Boat *fetched = get_boat(a, db, dawn->id, &rc);
   print_boat(fetched, NULL);

   printf("\n== creating competitors ==\n");
   Competitor *alice = create_competitor(a, db,
                                          &(CreateCompetitorParams){
                                              .first_name = to_sql_text("Alice"),
                                              .last_name = to_sql_text("Nguyen"),
                                              .email = to_sql_text("alice@example.com"),
                                              .boat_id = dawn->id,
                                          },
                                          &rc);
   print_competitor(alice);

   // No email/boat given — demonstrates nullable result columns (sql_nulltext,
   // sql_nullint64) coming back as .null = true.
   Competitor *bob = create_competitor_no_contact(a, db,
                                                   &(CreateCompetitorNoContactParams){
                                                       .first_name = to_sql_text("Bob"),
                                                       .last_name = to_sql_text("Reyes"),
                                                   },
                                                   &rc);
   print_competitor(bob);

   printf("\n== listing boats via the raw _cb primitive (borrowed strings) ==\n");
   list_boats_cb(db, print_boat, NULL);

   printf("\n== listing competitors via the owning wrapper ==\n");
   CompetitorList competitors = list_competitors(a, db, &rc);
   for (size_t i = 0; i < competitors.len; i++) print_competitor(&competitors.items[i]);

   printf("\n== giving bob an email ==\n");
   rc = update_competitor_email(db, &(UpdateCompetitorEmailParams){
                                         .email = to_sql_text("bob@example.com"),
                                         .id = bob->id,
                                     });
   if (rc != SQLITE_OK) die(db, "update_competitor_email");
   Competitor *bob2 = get_competitor(a, db, bob->id, &rc);
   print_competitor(bob2);

   printf("\n== recording catches for alice ==\n");
   create_catch(a, db,
                &(CreateCatchParams){
                    .competitor_id = alice->id,
                    .species = to_sql_text("Snapper"),
                    .weight_grams = 2300,
                    .caught_at = to_sql_text("2026-07-10"),
                },
                &rc);
   create_catch(a, db,
                &(CreateCatchParams){
                    .competitor_id = alice->id,
                    .species = to_sql_text("Kingfish"),
                    .weight_grams = 5400,
                    .caught_at = to_sql_text("2026-07-11"),
                },
                &rc);

   printf("\n== alice's catches ==\n");
   CatchList catches = list_catches_by_competitor(a, db, alice->id, &rc);
   sql_int64 total = 0;
   for (size_t i = 0; i < catches.len; i++) {
      print_catch(&catches.items[i]);
      total += catches.items[i].weight_grams;
   }
   printf("  total weight: %lldg\n", (long long)total);

   printf("\n== deleting bob, then trying to fetch him ==\n");
   rc = delete_competitor(db, bob->id);
   if (rc != SQLITE_OK) die(db, "delete_competitor");
   Competitor *gone = get_competitor(a, db, bob->id, &rc);
   printf("  get_competitor after delete: rc=%s result=%s\n",
          rc == SQLITE_NOTFOUND ? "SQLITE_NOTFOUND" : "unexpected", gone ? "non-NULL" : "NULL");

   sqlite3_close(db);
   return 0;
}
